### ISSUE TITLE
How to add base url at run time?

### ISSUE THREAD

**Issue by dseerapu** [abhigit-hub/base-mvvm#1]
Dear Abhigit,

How to add base URL at run time in this architecture?

Thanks,
Dharma Sai Seerapu.

**Comment by abhigit-hub** [comment]
You could try these two ways of doing it. Each one has its own drawback though

### **1. Using `@URL` Annotation**
You will have to set base URL to an empty string initially. And in the `AppApiHelper` class have an attribute for URL (with setters), which you can set up via `DataManager` as and when the URL is available at run time. Now, pass the URL for every N/W call in the `AppApiHelper,` and in the `ApiCall` class you will have to add an argument for every api call method with an `@Url` annotation.

This has more code repetitions, but is cleaner than 2.

### **2. Refreshing Dagger**
As the `ApiCall` instance is `@Singleton,` the application will have only one instance throughout the application cycle. In Dagger, we cannot refresh the `ApiCall` (for Base URL) instance alone. And removing the `@Singleton` may lead to multiple `ApiCall` instances per application cycle, which again is contradicting our purpose of using dagger.

I found a solution which could do the trick, but is a little hacky. The solution in the following link tries to refresh the whole dependency tree, and will lead to re-creation of all the dependencies from scratch. 
I don't think refreshing the dependency tree is a good idea.

**[S/O Link](https://stackoverflow.com/a/43165189)**

#### You can decide among the two based on how your use-case suits your call.

**Comment by dseerapu** [comment]
@abhigit-hub These I have tried already. But, none of these seems to be working fine.

Can we refresh a single module in runtime?

So, we can create setters and getters to the NetworkModule class.

**Comment by abhigit-hub** [comment]
@dseerapu 
Solution 1 will definitely work, but you will have to pass URL's for every API call in AppApiHelper, (i.e code repetitions). Have you tried Sol. 1?

AFAIK, Dagger-2 doesn't allow you to refresh modules. If you come across something on that, please do share. 

Ideally would not have setters/getters in the Network Module, but this is a workaround for your use case

**Comment by dseerapu** [comment]
@abhigit-hub 
I am saying that **Solution 1** is working fine for me. But, sending the **whole URL as the argument** with the annotation **@URL** is not good.

**Comment by abhigit-hub** [comment]
Agreed. But given your use case, you will have to figure out which solution works well for you
